using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TriviaClient.Utils
{
    enum RequestID : byte { LOGIN_REQUEST = 1, SIGNUP_REQUEST, GET_PLAYERS_IN_ROOM_REQUEST, JOIN_ROOM_REQUEST, CREATE_ROOM_REQUEST, SIGNOUT_REQUEST, GET_ROOMS_REQUEST, GET_HIGHSCORE, CLOSE_ROOM_REQUEST, START_GAME_REQUEST, GET_ROOM_STATE_REQUEST, LEAVE_ROOM_REQUEST };
    enum ResponseID : byte { ERROR_RESPONSE = 100, SIGNUP_RESPONSE, LOGIN_RESPONSE, CREATE_ROOM_RESPONSE, GET_PLAYERS_IN_ROOM_RESPONSE, GET_ROOMS_RESPONSE, HIGHSCORE_RESPONSE, JOIN_ROOM_RESPONSE, LOGOUT_RESPONSE, CLOSE_ROOM_RESPONSE, START_GAME_RESPONSE, GET_ROOM_STATE_RESPONSE, LEAVE_ROOM_RESPONSE };
}
